export const SELECT_CITY = 'SELECT_CITY'

export const REQUEST_WEATHER = 'REQUEST_WEATHER'
export const RECEIVE_WEATHER = 'RECEIVE_WEATHER'
export const FAILURE_WEATHER = 'FAILURE_WEATHER'

export const REQUEST_CITIES = 'REQUEST_CITIES'
export const RECEIVE_CITIES = 'RECEIVE_CITIES'

export const REQUEST_FORECAST = 'REQUEST_FORECAST'
export const RECEIVE_FORECAST = 'RECEIVE_FORECAST'

export const LOAD_FAVORITES_LIST = 'LOAD_FAVORITES_LIST'
export const CHANGE_FAVORITES = 'CHANGE_FAVORITES'
